version: "3"

services:
  go-battlemetrics-websocket-client:
    container_name: go-battlemetrics-websocket-client
    image: go-battlemetrics-websocket-client
    restart: unless-stopped
    environment:
      - "SERVERS=${SERVERS}"
